const wordBank = [
    { word: 'CAT', clue: 'Feline pet' },
    { word: 'DOG', clue: 'Man\'s best friend' },
    { word: 'SUN', clue: 'Star at center of solar system' },
    { word: 'MOON', clue: 'Earth\'s natural satellite' },
    { word: 'TREE', clue: 'Tall woody plant' },
    { word: 'BOOK', clue: 'Thing you read' },
    { word: 'OCEAN', clue: 'Large body of salt water' },
    { word: 'RIVER', clue: 'Flowing body of water' },
    { word: 'STAR', clue: 'Celestial body that shines' },
    { word: 'RAIN', clue: 'Water falling from clouds' },
    { word: 'SNOW', clue: 'Frozen precipitation' },
    { word: 'WIND', clue: 'Moving air' },
    { word: 'FIRE', clue: 'Hot glowing substance' },
    { word: 'BIRD', clue: 'Feathered flying animal' },
    { word: 'FISH', clue: 'Aquatic animal with gills' },
    { word: 'LION', clue: 'King of the jungle'},
    { word: 'BEAR', clue: 'Large mammal with thick fur' },
    { word: 'WOLF', clue: 'Wild canine' },
    { word: 'HORSE', clue: 'Domesticated hoofed animal' },
    { word: 'SNAKE', clue: 'Legless reptile' },
    { word: 'ELEPHANT', clue: 'Largest land animal' },
    { word: 'BRAIN', clue: 'Control center of the body' },
    { word: 'HEART', clue: 'Pumps blood through the body' },
    { word: 'MOUNTAIN', clue: 'Large natural elevation of the earth' },
    { word: 'VALLEY', clue: 'Low area between hills or mountains' },
    { word: 'ISLAND', clue: 'Land surrounded by water' },
    { word: 'DESERT', clue: 'Dry, arid region' },
    { word: 'FOREST', clue: 'Dense collection of trees' },
    { word: 'CLOUD', clue: 'Visible mass of condensed water vapor' },
    { word: 'RAINBOW', clue: 'Arc of colors in the sky' },
    { word: 'THUNDER', clue: 'Sound following lightning' },
    { word: 'LIGHTNING', clue: 'Electrical discharge in the atmosphere' },
    { word: 'VOLCANO', clue: 'Mountain that erupts lava' },
    { word: 'GLACIER', clue: 'Large mass of ice' },
    { word: 'CANYON', clue: 'Deep gorge' },
    { word: 'OASIS', clue: 'Fertile spot in a desert' },
    { word: 'CAVE', clue: 'Natural underground space' },
    {word: 'WHALE', clue: 'Large marine mammal' },
    {word: 'OCEAN', clue: 'Vast body of salt water' },
    {word: 'EURASIA', clue: 'Largest continent' },
    {word: 'AFRICA', clue: 'Continent known for its wildlife' },
    {word: 'JUPITER', clue: 'Largest planet in our solar system' },
    { word: 'APPLE', clue: 'Red or green fruit' },
    { word: 'BREAD', clue: 'Used for sandwiches' },
    { word: 'CHAIR', clue: 'You sit on it' },
    { word: 'SHOE', clue: 'Worn on your foot' },
    { word: 'HOUSE', clue: 'Place where you live' },
    { word: 'CAR', clue: 'Vehicle with four wheels' },
    { word: 'MILK', clue: 'White drink from cows' },
    { word: 'EGG', clue: 'Breakfast food from chickens' },
    { word: 'DOG', clue: 'Barks and wags tail' },
    { word: 'CAT', clue: 'Purrs and chases mice' },
    { word: 'HAND', clue: 'At the end of your arm' },
    { word: 'FOOT', clue: 'At the end of your leg' },
    { word: 'NOSE', clue: 'Used to smell' },
    { word: 'EAR', clue: 'Used to hear' },
    { word: 'EYE', clue: 'Used to see' },
    { word: 'BAG', clue: 'Used to carry things' },
    { word: 'COAT', clue: 'Worn when it is cold' },
    { word: 'HAT', clue: 'Worn on your head' },
    { word: 'SOAP', clue: 'Used to wash hands' },
    { word: 'FORK', clue: 'Used to eat food' },
    { word: 'SPOON', clue: 'Used for soup' },
    { word: 'CUP', clue: 'Used for tea or coffee' },
    { word: 'DOOR', clue: 'You open it to enter' },
    { word: 'BED', clue: 'You sleep on it' },
    { word: 'PEN', clue: 'Used to write' },
    { word: 'BOOK', clue: 'You read it' },
    { word: 'CHAIR', clue: 'You sit on it' },
    { word: 'TABLE', clue: 'You eat at it' },
    { word: 'FISH', clue: 'Lives in water' },
    { word: 'BIRD', clue: 'Has wings and flies' },
    { word: 'DUCK', clue: 'Quacks and swims' },
    { word: 'COW', clue: 'Gives milk' },
    { word: 'PIG', clue: 'Says oink' },
    { word: 'HORSE', clue: 'You can ride it' },
    { word: 'SHEEP', clue: 'Has wool' },
    { word: 'GOAT', clue: 'Has horns and eats grass' },
    { word: 'SUN', clue: 'Shines in the sky' },
    { word: 'MOON', clue: 'Seen at night' },
    { word: 'STAR', clue: 'Twinkles in the sky' },
    { word: 'RAIN', clue: 'Falls from clouds' },
    { word: 'SNOW', clue: 'White and cold' },
    { word: 'WIND', clue: 'Moves the leaves' },
    { word: 'TREE', clue: 'Has leaves and branches' },
    { word: 'GRASS', clue: 'Green and grows in yards' },
    { word: 'LEAF', clue: 'Grows on a tree' },
    { word: 'ROOT', clue: 'Underground part of a plant' },
    { word: 'BELL', clue: 'Rings when you shake it' },
    { word: 'BALL', clue: 'Round and used in games' },
    { word: 'TOY', clue: 'Children play with it' }
];


let grid = [];
let words = [];
const GRID_SIZE = 10;



 